### PR TITLE
Modularize CMake builds

### PR DESCRIPTION
**Pull request by kalyan-kumar**
Each of our directories now builds into a separate library. In a commit over this, I will separate mkfs into a separate binary.

### CODE REVIEW

**Review by mr-bat — APPROVED** [review]
Looks fine to me.

**Comment by mr-bat** [comment]
Btw, is there any reason that you don't use the squash and merge feature? It will produce only one commit too.

**Comment by kalyan-kumar** [comment]
While developing, if we make commits for every small change - I mean like small typo fixes sort - I don't want those to appear separately on the repo at all. One commit must be a small feature, but in it's entirety. By squashing those small commits on github, the commit message still becomes bloated. So, I just prefer the command line. Or I am not making sense and simply am comfortable with what I'm used to :P.

**Comment by kalyan-kumar** [comment]
Rebase and merge is what I feel is the best and keeps the repo cleanest.

**Pull request merged**
